INSERT INTO CLIENT (CLIENT_ID, FIRST_NAME, LAST_NAME, USER_NAME) VALUES
  (1, 'Donald', 'Trump', 'dtrump'),
  (2, 'Joe', 'Biden', 'jbiden');
  
INSERT INTO ACCOUNT  (ACCOUNT_ID, ACCOUNT_NUMBER, ACCOUNT_TYPE, BALANCE, CLIENT_ID) VALUES
  (1,1000,'1',0.0,1),
  (2,1001,'1',0.0,2);